### ISSUE TITLE
Cannot create log file error

### ISSUE THREAD

**Issue by rekka** [substantic/rain#28]
```bash
$ ./rain start --worker-host-file=hosts.txt
🌧  INFO 2018-04-11T08:15:45Z Starting Rain 0.2.0
🌧  INFO 2018-04-11T08:15:45Z Log directory: /tmp/rain-logs/worker-p1-16085
🌧  INFO 2018-04-11T08:15:45Z Starting local server (0.0.0.0:7210)
🌧  INFO 2018-04-11T08:15:45Z Dashboard: http://p1:8080/
🌧  INFO 2018-04-11T08:15:45Z Server pid = 16086
🌧  INFO 2018-04-11T08:15:45Z Process 'server' is ready
🌧  INFO 2018-04-11T08:15:45Z Starting 1 remote worker(s)
🌧  INFO 2018-04-11T08:15:45Z Connecting to jupiter (remote log dir: "/tmp/rain-logs/worker-p1-16085")
🌧 ERROR 2018-04-11T08:15:45Z Remote process at jupiter, the following error occurs: Cannot create log file

🌧  INFO 2018-04-11T08:15:45Z Error occurs; clean up started processes ...
```
I believe the log directory should be created first by calling `mkdir -p {log_dir}` before trying to create the log file at https://github.com/substantic/rain/blob/f3ec16c96409e1e6ffc9fa0d4688fb110c9d9970/src/start/ssh.rs#L98

`touch` does not create parent directories on my Debian server.

**Comment by spirali** [comment]
I have put a fix into the master. Can you please check that it helps you?

**Comment by spirali** [comment]
Please let me know if you are using binary distribution, I can generate a binary of Rain for you.

**Comment by rekka** [comment]
Thanks for the quick fix. Yes, this seems to work (I compiled it directly with `cargo build --release`). Now I just fail with `ERROR 2018-04-11T08:34:24Z: rain: Cannot resolve server address` in `worker-0.err`, but that is because my desktop is behind a router I believe, so not accessible from the remote host.

**Comment by spirali** [comment]
The current version uses hostname of machine where "rain start" is executed as the server address for workers. Hence, if workers does not know this hostname (e.g. because it is just internal hostname) then it may also fails. I can make it configurable if this is your problem. I also plan to implement possibility to start remote server via "rain start", that could also help with your scenario. Right now, running "rain start" directly on the remote machine and use only client on the desktop could help you.

**Comment by rekka** [comment]
Cool, thanks, that works.

**Comment by rekka** [comment]
Cool, thanks, that works for me.

**Comment by spirali** [comment]
Ok, I am closing this issue. Thank you for reporting.
